before_install:
  - git fetch origin master:master
  - git fetch origin v2.0.0:v2.0.0
  - sudo apt-get install libicu-dev -y
before_script:
  - bundle exec rake samples
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
notifications:
  disabled: true
