sudo: false
before_install:
  - git fetch origin master:master
  - git fetch origin v2.0.0:v2.0.0
  - git fetch origin test/attributes:test/attributes
  - git fetch origin test/master:test/master
  - sudo apt-get install libicu-dev -y
  - git submodule init
  - git submodule sync --quiet
  - script/fast-submodule-update
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
notifications:
  disabled: true
git:
  submodules: false
