language: ruby
sudo: false

addons:
  apt:
    packages:
    - libicu-dev
    - libicu52

before_install: script/travis/before_install

script:
  - bundle exec rake
  - script/licensed status

rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.1


notifications:
  disabled: true

git:
  submodules: false
  depth: 3

cache: bundler
dist: trusty

bundler_args: --without debug
